sudo: required
language: csharp
solution: antbear-dotnet.csproj
mono: none
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet restore && dotnet build
